"""Added academic sessions and sections

Revision ID: 699ff795d841
Revises: 9c7bf59743da
Create Date: 2025-10-06 00:01:41.811396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699ff795d841'
down_revision = '9c7bf59743da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
