"""Implement detailed college structure

Revision ID: 8ff151fe6422
Revises: faec6aa344d4
Create Date: 2025-10-02 02:58:19.098150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ff151fe6422'
down_revision = 'faec6aa344d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_departments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'department_id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.drop_column('professor')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('admission_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['college_id'])
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.drop_column('reset_token_expiration')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('moderated_department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moderated_department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiration', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('department_id')
        batch_op.drop_column('admission_year')
        batch_op.drop_column('college_id')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('section')

    op.drop_table('professor_departments')
    op.drop_table('departments')
    op.drop_table('courses')
    # ### end Alembic commands ###
