"""Added many-to-many relationship for notes and sections

Revision ID: 913e42e8e1d9
Revises: ad5cb8b50d98
Create Date: 2025-10-17 23:14:10.984427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '913e42e8e1d9'
down_revision = 'ad5cb8b50d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('section')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))

    # ### end Alembic commands ###
