"""Add section and department to notes

Revision ID: d867530118fc
Revises: 699ff795d841
Create Date: 2025-10-16 20:24:11.680212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd867530118fc'
down_revision = '699ff795d841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'])
        batch_op.drop_column('section')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
